-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.alternative_investitionen (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  mitglied_id uuid NOT NULL,
  typ character varying NOT NULL,
  bezeichnung character varying NOT NULL,
  anschaffungsdatum date NOT NULL,
  anschaffungskosten_gesamt numeric NOT NULL,
  anschaffungskosten_alternativ numeric,
  anschaffungskosten_relevant numeric DEFAULT (anschaffungskosten_gesamt - COALESCE(anschaffungskosten_alternativ, (0)::numeric)),
  alternativ_beschreibung character varying,
  kosten_jahr_aktuell jsonb DEFAULT '{}'::jsonb,
  kosten_jahr_alternativ jsonb DEFAULT '{}'::jsonb,
  einsparungen_jahr jsonb DEFAULT '{}'::jsonb,
  einsparung_gesamt_jahr numeric,
  parameter jsonb DEFAULT '{}'::jsonb,
  co2_einsparung_kg_jahr numeric,
  aktiv boolean DEFAULT true,
  notizen text,
  erstellt_am timestamp without time zone DEFAULT now(),
  aktualisiert_am timestamp without time zone DEFAULT now(),
  parent_investition_id uuid,
  CONSTRAINT alternative_investitionen_pkey PRIMARY KEY (id),
  CONSTRAINT alternative_investitionen_mitglied_id_fkey FOREIGN KEY (mitglied_id) REFERENCES public.mitglieder(id),
  CONSTRAINT alternative_investitionen_parent_investition_id_fkey FOREIGN KEY (parent_investition_id) REFERENCES public.alternative_investitionen(id)
);
CREATE TABLE public.anlagen (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mitglied_id uuid NOT NULL,
  anlagenname text NOT NULL,
  anlagentyp text DEFAULT 'Solar'::text,
  installationsdatum date NOT NULL,
  leistung_kwp numeric NOT NULL CHECK (leistung_kwp > 0::numeric),
  hersteller text,
  modell text,
  anzahl_module integer CHECK (anzahl_module > 0),
  wechselrichter_modell text,
  ausrichtung text,
  neigungswinkel_grad integer CHECK (neigungswinkel_grad >= 0 AND neigungswinkel_grad <= 90),
  batteriekapazitaet_kwh numeric CHECK (batteriekapazitaet_kwh >= 0::numeric),
  batterie_hersteller text,
  batterie_modell text,
  standort_strasse text,
  standort_plz text,
  standort_ort text,
  standort_latitude numeric,
  standort_longitude numeric,
  anschaffungskosten_gesamt numeric CHECK (anschaffungskosten_gesamt >= 0::numeric),
  anschaffungskosten_speicher numeric CHECK (anschaffungskosten_speicher >= 0::numeric),
  ekfz_vorhanden boolean DEFAULT false,
  ekfz_modell text,
  ekfz_speicher_kwh numeric CHECK (ekfz_speicher_kwh >= 0::numeric),
  ekfz_verbrauch_kwh_100km numeric CHECK (ekfz_verbrauch_kwh_100km >= 0::numeric),
  notizen text,
  aktiv boolean DEFAULT true,
  erstellt_am timestamp with time zone DEFAULT now(),
  batterie_bezeichnung text,
  ekfz_bezeichnung text,
  waermepumpe_bezeichnung text,
  sonstiges text,
  profilbeschreibung text,
  CONSTRAINT anlagen_pkey PRIMARY KEY (id),
  CONSTRAINT anlagen_mitglied_id_fkey FOREIGN KEY (mitglied_id) REFERENCES public.mitglieder(id)
);
CREATE TABLE public.anlagen_freigaben (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  anlage_id uuid NOT NULL UNIQUE,
  profil_oeffentlich boolean DEFAULT false,
  kennzahlen_oeffentlich boolean DEFAULT false,
  auswertungen_oeffentlich boolean DEFAULT false,
  investitionen_oeffentlich boolean DEFAULT false,
  monatsdaten_oeffentlich boolean DEFAULT false,
  standort_genau boolean DEFAULT false,
  erstellt_am timestamp with time zone DEFAULT now(),
  aktualisiert_am timestamp with time zone DEFAULT now(),
  CONSTRAINT anlagen_freigaben_pkey PRIMARY KEY (id),
  CONSTRAINT anlagen_freigaben_anlage_id_fkey FOREIGN KEY (anlage_id) REFERENCES public.anlagen(id)
);
CREATE TABLE public.investition_monatsdaten (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  investition_id uuid NOT NULL,
  jahr integer NOT NULL,
  monat integer NOT NULL CHECK (monat >= 1 AND monat <= 12),
  verbrauch_daten jsonb DEFAULT '{}'::jsonb,
  kosten_daten jsonb DEFAULT '{}'::jsonb,
  einsparung_monat_euro numeric,
  co2_einsparung_kg numeric,
  notizen text,
  erstellt_am timestamp without time zone DEFAULT now(),
  aktualisiert_am timestamp without time zone DEFAULT now(),
  betriebsausgaben_monat_euro numeric DEFAULT 0,
  CONSTRAINT investition_monatsdaten_pkey PRIMARY KEY (id),
  CONSTRAINT investition_monatsdaten_investition_id_fkey FOREIGN KEY (investition_id) REFERENCES public.alternative_investitionen(id)
);
CREATE TABLE public.mitglieder (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  vorname text NOT NULL,
  nachname text NOT NULL,
  strasse text,
  plz text,
  ort text,
  latitude numeric,
  longitude numeric,
  telefon text,
  beitrittsdatum date DEFAULT CURRENT_DATE,
  erstellt_am timestamp with time zone DEFAULT now(),
  aktiv boolean DEFAULT true,
  CONSTRAINT mitglieder_pkey PRIMARY KEY (id)
);
CREATE TABLE public.monatsdaten (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  anlage_id uuid NOT NULL,
  mitglied_id uuid NOT NULL,
  jahr integer NOT NULL CHECK (jahr >= 2000 AND jahr <= 2100),
  monat integer NOT NULL CHECK (monat >= 1 AND monat <= 12),
  gesamtverbrauch_kwh numeric CHECK (gesamtverbrauch_kwh >= 0::numeric),
  pv_erzeugung_kwh numeric CHECK (pv_erzeugung_kwh >= 0::numeric),
  direktverbrauch_kwh numeric CHECK (direktverbrauch_kwh >= 0::numeric),
  batterieentladung_kwh numeric CHECK (batterieentladung_kwh >= 0::numeric),
  batterieladung_kwh numeric CHECK (batterieladung_kwh >= 0::numeric),
  netzbezug_kwh numeric CHECK (netzbezug_kwh >= 0::numeric),
  einspeisung_kwh numeric CHECK (einspeisung_kwh >= 0::numeric),
  ekfz_ladung_kwh numeric CHECK (ekfz_ladung_kwh >= 0::numeric),
  netzbezug_kosten_euro numeric CHECK (netzbezug_kosten_euro >= 0::numeric),
  einspeisung_ertrag_euro numeric CHECK (einspeisung_ertrag_euro >= 0::numeric),
  grundpreis_euro numeric CHECK (grundpreis_euro >= 0::numeric),
  netzbezugspreis_cent_kwh numeric,
  einspeiseverguetung_cent_kwh numeric,
  notizen text,
  erfasst_am timestamp with time zone DEFAULT now(),
  aktualisiert_am timestamp with time zone,
  betriebsausgaben_monat_euro numeric DEFAULT 0,
  CONSTRAINT monatsdaten_pkey PRIMARY KEY (id),
  CONSTRAINT monatsdaten_anlage_id_fkey FOREIGN KEY (anlage_id) REFERENCES public.anlagen(id),
  CONSTRAINT monatsdaten_mitglied_id_fkey FOREIGN KEY (mitglied_id) REFERENCES public.mitglieder(id)
);
CREATE TABLE public.wetterdaten (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  plz text NOT NULL,
  datum date NOT NULL,
  jahr integer NOT NULL CHECK (jahr >= 2000 AND jahr <= 2100),
  monat integer NOT NULL CHECK (monat >= 1 AND monat <= 12),
  sonnenstunden numeric CHECK (sonnenstunden >= 0::numeric),
  globalstrahlung_kwh_m2 numeric CHECK (globalstrahlung_kwh_m2 >= 0::numeric),
  temperatur_durchschnitt_c numeric,
  datenquelle text,
  erstellt_am timestamp with time zone DEFAULT now(),
  CONSTRAINT wetterdaten_pkey PRIMARY KEY (id)
);